### ISSUE TITLE
The latest pip version is breaking the design

### ISSUE THREAD

**Issue by say2sankalp** [donnemartin/haxor-news#139] opened 2018-05-23 07:41 UTC
**Pip version: 10.0.0**
Python version: 3.6.5 && 2.7.14
Operating system: macOS 10.13.5

**Description:**
for dist in pip.get_installed_distributions():
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**What I've run:**
pip.get_installed_distributions()

**Comment by donnemartin** [comment] 2018-07-26 02:40
@say2sankalp thanks for reporting the issue!

**Comment by donnemartin** [comment] 2019-02-17 12:00
Hi @say2sankalp are you still seeing this issue?  If so, what's your workflow?

I don't see this with pip 19.0.2, Python 3.7.2

**Comment by donnemartin** [comment] 2019-04-13 15:45
Closing out, I'm not able to reproduce with a later version of pip.

**Closed by donnemartin** 2019-04-13 15:45 UTC
Labels: question, response-needed

**Comment by say2sankalp** [comment] 2019-04-14 22:01
its safe to close
